### PR TITLE
Update README.md with a more descriptive design

### PR DESCRIPTION
**Pull request by ragulpr**
Hey I just continued thinking about this a bit while it was on my mind. Mind if I add this for posterity? It's just adding some designs I documented in #4

### CODE REVIEW

**Review by angeldzzz23 — APPROVED** [review]
Looks good on my end.

**Review by 62neo62 — APPROVED** [review]
Looks like a solid blueprint. Comms/sensors/hardware details check out

**Review by tigran-iii — APPROVED** [review]
seems to add a lot of clarity, thank you for the contribution. please keep me in the loop, if you continue working on this project.

**Review by yurkoturskiy — APPROVED** [review]
Looks awesome. Thanks for writing it down.

**Comment by ragulpr** [comment]
Thanks all!! I hope this is close to sum total of all the ideas you had during the hack, thought it was fun to have it stored away somewhere 🌞

**Pull request merged**
